openapi: 3.0.1
info:
  title: Documentación del poder y del saber
  version: 1.0.0
  description: API pensada para clase de Swagger

paths:
  /api/adoptions/{uid}/{pid}:
    post:
      summary: Se adopta una mascota 
      tags:
        - Adoptions
      parameters:
        - name: uid
          in: path
          required: true
          description: Id del usuario que se desea solicitar.
          schema:
            type: string
        - name: pid
          in: path
          required: true
          description: Id dela mascota que se desea solicitar.
          schema:
            type: string
      responses:
        "200":
          description: Se realiza una adopcion
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Pet adopted
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo de conexión con la base de datos
