apiVersion: v1
kind: Service
metadata:
  name: adoptmeservice
spec:
  selector:
    app: adoptmepod
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30008  # 30000 hasta 32767
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: adoptmedeployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: adoptmepod
  template:
    metadata:
      labels:
        app: adoptmepod
    spec:
      containers:
      - name: adoptmecontainer
        image: maxirosanda/adoptmesabado31052025:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URI
          value: "mongodb+srv://maxirosanda:sdTQXhZ1hwIxXu3q@cluster0.wh168.mongodb.net/backendsabados?retryWrites=true&w=majority&appName=Cluster0"
        - name: MODE
          value: "prod"
        imagePullPolicy: Always
